version: "3.8"

services:
  admin:
    container_name: admin-${NODE_ENV}
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    restart: always
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - ./apps/admin/.env.${NODE_ENV}
    depends_on:
      - backend

  backend:
    container_name: backend-${NODE_ENV}
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env.${NODE_ENV}
